package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val Surface = Color(0xFFFFF8F6)
val OnSurface = Color(0xFF1C1B1B)
val SurfaceVariant = Color(0xFFE7E0DC)
val TertiaryContainer = Color(0xFFFFDAD4)
val OnTertiaryContainer = Color(0xFF410001)
val Tertiary = Color(0xFFBC4A2A)
val ErrorColor = Color(0xFFBA1A1A)
val TertiaryFixed = Color(0xFFFFDAD4)
val PrimaryFixed = Color(0xFFFFDAD4)
val OnPrimaryFixed = Color(0xFF1C1B1B)
val OnPrimaryFixedVariant = Color(0xFF49454E)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF5F0EE)
val SurfaceContainer = Color(0xFFF0EAE7)
val SurfaceContainerHigh = Color(0xFFEAE4E1)
val SurfaceContainerHighest = Color(0xFFE0D8D5)
val OutlineVariant = Color(0xFFC8C5C0)
val Outline = Color(0xFF797670)
val SecondaryContainer = Color(0xFFB71C1C)
val OnSecondaryContainer = Color(0xFFFFFFFF)
val SecondaryFixed = Color(0xFFE7E0DC)
val OnSecondaryFixed = Color(0xFF1C1B1B)
val OnSecondaryFixedVariant = Color(0xFF6A5F5F)
val OnSurfaceVariant = Color(0xFF49454E)
val Primary = Color(0xFFB71C1C)

val PrimaryRed = Color(0xFFB71C1C)
val OnPrimaryRed = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFFFDAD4)
val OnPrimaryContainer = Color(0xFF410001)
val SecondaryRed = Color(0xFFE53935)
val SurfaceTint = Color(0xFFB71C1C)
